// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

type HelloResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 关于自定义类型
type  MutiHellRequest struct {
	Id                   []int64               `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Time                 *MutiHellRequest_Time `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MutiHellRequest) Reset()         { *m = MutiHellRequest{} }
func (m *MutiHellRequest) String() string { return proto.CompactTextString(m) }
func (*MutiHellRequest) ProtoMessage()    {}
func (*MutiHellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *MutiHellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutiHellRequest.Unmarshal(m, b)
}
func (m *MutiHellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutiHellRequest.Marshal(b, m, deterministic)
}
func (m *MutiHellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutiHellRequest.Merge(m, src)
}
func (m *MutiHellRequest) XXX_Size() int {
	return xxx_messageInfo_MutiHellRequest.Size(m)
}
func (m *MutiHellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutiHellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutiHellRequest proto.InternalMessageInfo

func (m *MutiHellRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MutiHellRequest) GetTime() *MutiHellRequest_Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type MutiHellRequest_Time struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutiHellRequest_Time) Reset()         { *m = MutiHellRequest_Time{} }
func (m *MutiHellRequest_Time) String() string { return proto.CompactTextString(m) }
func (*MutiHellRequest_Time) ProtoMessage()    {}
func (*MutiHellRequest_Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2, 0}
}

func (m *MutiHellRequest_Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutiHellRequest_Time.Unmarshal(m, b)
}
func (m *MutiHellRequest_Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutiHellRequest_Time.Marshal(b, m, deterministic)
}
func (m *MutiHellRequest_Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutiHellRequest_Time.Merge(m, src)
}
func (m *MutiHellRequest_Time) XXX_Size() int {
	return xxx_messageInfo_MutiHellRequest_Time.Size(m)
}
func (m *MutiHellRequest_Time) XXX_DiscardUnknown() {
	xxx_messageInfo_MutiHellRequest_Time.DiscardUnknown(m)
}

var xxx_messageInfo_MutiHellRequest_Time proto.InternalMessageInfo

func (m *MutiHellRequest_Time) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MutiHellRequest_Time) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type MutiHellResponse struct {
	Id                   []int64  `protobuf:"varint,2,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutiHellResponse) Reset()         { *m = MutiHellResponse{} }
func (m *MutiHellResponse) String() string { return proto.CompactTextString(m) }
func (*MutiHellResponse) ProtoMessage()    {}
func (*MutiHellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *MutiHellResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutiHellResponse.Unmarshal(m, b)
}
func (m *MutiHellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutiHellResponse.Marshal(b, m, deterministic)
}
func (m *MutiHellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutiHellResponse.Merge(m, src)
}
func (m *MutiHellResponse) XXX_Size() int {
	return xxx_messageInfo_MutiHellResponse.Size(m)
}
func (m *MutiHellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutiHellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutiHellResponse proto.InternalMessageInfo

func (m *MutiHellResponse) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "hello.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "hello.HelloResponse")
	proto.RegisterType((*MutiHellRequest)(nil), "hello.MutiHellRequest")
	proto.RegisterType((*MutiHellRequest_Time)(nil), "hello.MutiHellRequest.Time")
	proto.RegisterType((*MutiHellResponse)(nil), "hello.MutiHellResponse")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbf, 0x4e, 0xc4, 0x30,
	0x0c, 0xc6, 0x49, 0xd2, 0x43, 0xe0, 0x83, 0xe3, 0x64, 0x6e, 0xa8, 0x8e, 0xa5, 0x0a, 0x4b, 0xa7,
	0x20, 0x1d, 0x03, 0x8f, 0x00, 0x0b, 0x4b, 0xca, 0x0b, 0x14, 0x6a, 0x89, 0x48, 0x6d, 0x53, 0x9a,
	0x14, 0x89, 0x95, 0x27, 0x47, 0xf9, 0x83, 0xf8, 0xb3, 0x7d, 0x9f, 0x65, 0x7f, 0xfe, 0xd9, 0xb0,
	0x7e, 0xa5, 0xbe, 0xb7, 0x6a, 0x9a, 0xad, 0xb7, 0xb8, 0x8a, 0x46, 0x6e, 0xe0, 0xec, 0x21, 0x08,
	0x4d, 0x6f, 0x0b, 0x39, 0x2f, 0xaf, 0xe1, 0x3c, 0x7b, 0x37, 0xd9, 0xd1, 0x11, 0x22, 0x14, 0x63,
	0x3b, 0x50, 0xc9, 0x2a, 0x56, 0x9f, 0xea, 0xa8, 0xe5, 0x27, 0x83, 0x8b, 0xc7, 0xc5, 0x9b, 0xd0,
	0x99, 0x07, 0x71, 0x03, 0xdc, 0x74, 0x25, 0xab, 0x44, 0x2d, 0x34, 0x37, 0x1d, 0xde, 0x40, 0xe1,
	0xcd, 0x40, 0x25, 0xaf, 0x58, 0xbd, 0x3e, 0x5c, 0xa9, 0xb4, 0xfb, 0xdf, 0x94, 0x7a, 0x32, 0x03,
	0xe9, 0xd8, 0xb8, 0x57, 0x50, 0x04, 0x87, 0x3b, 0x58, 0x39, 0xdf, 0xce, 0x3e, 0x6e, 0x14, 0x3a,
	0x19, 0xdc, 0x82, 0xa0, 0xb1, 0x8b, 0x69, 0x42, 0x07, 0x29, 0x25, 0x6c, 0x7f, 0xd2, 0x32, 0x6c,
	0x82, 0xe0, 0xdf, 0x10, 0x87, 0xfb, 0x7c, 0x5d, 0x43, 0xf3, 0xbb, 0x79, 0x21, 0xbc, 0x83, 0x93,
	0xe6, 0xa3, 0x8d, 0x25, 0xbc, 0xcc, 0x48, 0xbf, 0xcf, 0xdf, 0xef, 0xfe, 0x16, 0x53, 0xac, 0x3c,
	0x7a, 0x3e, 0x8e, 0x4f, 0xbb, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x19, 0x3d, 0x5f, 0x9a, 0x43,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	SyaHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SyaHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/SyaHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	SyaHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) SyaHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyaHello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SyaHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SyaHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/SyaHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SyaHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyaHello",
			Handler:    _HelloService_SyaHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
